# Generated by Django 2.2 on 2020-06-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_name',
        ),
    ]
