# Generated by Django 2.2 on 2020-06-29 14:12

from django.db import migrations
import online_market.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200629_1349'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', online_market.users.models.CustomUserManager()),
            ],
        ),
    ]
