# Generated by Django 2.2 on 2020-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200629_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='count',
        ),
    ]
