# Generated by Django 2.2 on 2020-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
